ScicraftLearn/Minelabs

- build.gradle
- settings.gradle
- src/main/java/be/uantwerpen/scicraft/Scicraft.java
- src/main/java/be/uantwerpen/scicraft/entity/Entities.java
- src/main/java/be/uantwerpen/scicraft/entity/EntropyCreeperEntity.java
- src/main/java/be/uantwerpen/scicraft/mixins/CreeperEntityMixin.java
- src/main/java/be/uantwerpen/scicraft/renderer/EntropyCreeperEntityRenderer.java
- src/main/resources/assets/scicraft/lang/en_us.json
- src/main/resources/assets/scicraft/lang/nl_be.json
- src/main/resources/fabric.mod.json
- src/main/resources/scicraft.mixins.json
Solves #18, #9
Used default Creeper Spawn settings.
Done:
- Added info for testing ( 'BiomSelectors.all()' and enter End/Nether)
- Change 'getClosestPlayer(... ,false)' for testing
Refinement:
- Add Configurable Spawn Settings (Biomes list, spawnrate,....)
> Entropy Creeper Enhancements

- build.gradle
- gradle.properties
- settings.gradle
- src/main/java/be/uantwerpen/scicraft/Scicraft.java
- src/main/java/be/uantwerpen/scicraft/entity/Entities.java
- src/main/java/be/uantwerpen/scicraft/entity/EntropyCreeperEntity.java
- src/main/java/be/uantwerpen/scicraft/mixins/CreeperEntityMixin.java
- src/main/java/be/uantwerpen/scicraft/renderer/EntropyCreeperEntityRenderer.java
- src/main/resources/assets/scicraft/lang/en_us.json
- src/main/resources/assets/scicraft/lang/nl_be.json
- src/main/resources/fabric.mod.json
- src/main/resources/scicraft.mixins.json
Update to minecraft 1.18
- Fabric loader updated
- Java Dependency updated (JAVA 17)
- WTHIT updated (1.18 compatible version)
- Mappings updated for 1.18
> update to 1.18

- src/main/java/be/uantwerpen/scicraft/ExtraDispenserBehavior.java
> Fixes Dispenser behaviour for Entropy Creeper Spawn Egg

- src/main/java/be/uantwerpen/scicraft/entity/EntropyCreeperEntity.java
- src/main/java/be/uantwerpen/scicraft/mixins/ExplosionAccessor.java
- src/main/resources/scicraft.mixins.json
> Entropy creeper use explosion radius to select blocks and animate shuffling over 5 ticks

- src/main/java/be/uantwerpen/scicraft/entity/EntropyCreeperEntity.java
Solves #65 
- Added Check for empty blockList (you never know)
- Override EffectiveResistance of Entity (no resistance pls, `0f` )
> fixed Entropy Creeper explosion in water

- build.gradle
- gradle.properties
- src/main/java/be/uantwerpen/scicraft/paintings/Paintings.java
- src/main/java/be/uantwerpen/scicraft/renderer/ChargedBlockEntityRenderer.java
- src/main/java/be/uantwerpen/scicraft/util/Tags.java
- src/main/resources/data/minecraft/tags/painting_variant/placeable.json
- src/main/resources/fabric.mod.json
Updated to minecraft 1.19 (Workshop version, main is behind)
Disabled/removed WTHIT bugs in current verions.
> Versioning

- build.gradle
- gradle.properties
- src/main/java/be/uantwerpen/scicraft/ExtraDispenserBehavior.java
- src/main/java/be/uantwerpen/scicraft/entity/EntropyCreeperEntity.java
- src/main/java/be/uantwerpen/scicraft/paintings/Paintings.java
- src/main/java/be/uantwerpen/scicraft/renderer/ChargedBlockEntityRenderer.java
- src/main/java/be/uantwerpen/scicraft/util/Tags.java
- src/main/resources/data/minecraft/tags/painting_variant/placeable.json
- src/main/resources/fabric.mod.json
Hand picked update commits of workshop update, but for main.
> Version 1 19 main

- src/main/java/be/uantwerpen/scicraft/item/ItemGroups.java
- src/main/java/be/uantwerpen/scicraft/item/Items.java
- src/main/resources/assets/scicraft/lang/en_us.json
- src/main/resources/assets/scicraft/lang/nl_be.json
Fixed a creative tab icon
moved atoms to their own creative tab
> Creative tabs fix

- src/main/java/be/uantwerpen/scicraft/block/ChargedBlock.java
Ik ga hier mijn aanpassingen aan de coulomb kracht verzamelen. Ik heb al beweging, maar soms lijkt er nog iets fout te gaan.
> Coulomb Kracht

- src/main/java/be/uantwerpen/scicraft/block/ChargedBlock.java
- src/main/java/be/uantwerpen/scicraft/block/TimeFreezeBlock.java
- src/main/java/be/uantwerpen/scicraft/block/entity/ChargedBlockEntity.java
- src/main/java/be/uantwerpen/scicraft/renderer/ChargedBlockEntityRenderer.java
This branch has most of the code for the electric field and the coulomb force. Also the time freeze block is added here and I believe it works as it should. It stops all the charged animations from happening when it's in range.
> Time freeze block

- src/main/java/be/uantwerpen/minelabs/entity/EntropyCreeperEntity.java
> entropycreeper: change import that crashes server

- src/main/java/be/uantwerpen/minelabs/block/Blocks.java
- src/main/java/be/uantwerpen/minelabs/block/IonicBlock.java
- src/main/java/be/uantwerpen/minelabs/block/LewisBlock.java
- src/main/resources/assets/minelabs/blockstates/ionic_block.json
- src/main/resources/assets/minelabs/blockstates/lewis_block.json
Added Water logging for Lewis Crafting table and Ionic Crafting table.
fixes #362 & fixes #361
> Water logging and other fixes

- build.gradle
- gradle.properties
Loom finally updated to V1 (1.0-SNAPSHOT)
yarn-mappings updated to 1.19.2+build.18 (was 8)
wthit updated to 5.12.0 (was 5.11.3)
> updated minecraft build version + full release Loom

- src/main/java/be/uantwerpen/minelabs/Minelabs.java
- src/main/java/be/uantwerpen/minelabs/block/BohrBlock.java
- src/main/java/be/uantwerpen/minelabs/block/PortalBlock.java
- src/main/java/be/uantwerpen/minelabs/event/ServerModEvents.java
- src/main/java/be/uantwerpen/minelabs/util/NuclidesTable.java
- src/main/resources/assets/minelabs/lang/en_us.json
- src/main/resources/assets/minelabs/lang/nl_be.json
- src/main/resources/assets/minelabs/models/item/manganese_atom.json
- src/main/resources/assets/minelabs/models/item/titanium_atom.json
- src/main/resources/assets/minelabs/models/item/tungsten_atom.json
Fixed NucleusTable not loading when outside of IntelliJ. (fixes #369)
Added a creative check for Bohr Plate (Place able in Creative anywhere)  (fixes #337)
Some cleanup for Bohr plate and Portal block (which might be redundant since we are introducing a beter portal)
> Bohr fixes

- src/main/java/be/uantwerpen/minelabs/MinelabsClient.java
- src/main/java/be/uantwerpen/minelabs/block/Blocks.java
- src/main/java/be/uantwerpen/minelabs/block/entity/BlockEntities.java
- src/main/java/be/uantwerpen/minelabs/block/entity/ChargedBlockEntity.java
- Add cutout for the Anti-Proton
- Make Anti-Proton stable
- Make Anti-Proton negative
> - Close #281 and merge branch main_issue281

- src/main/java/be/uantwerpen/minelabs/crafting/molecules/Atom.java
> Lewis algo gittinggud

- src/main/java/be/uantwerpen/minelabs/MinelabsClient.java
- src/main/java/be/uantwerpen/minelabs/block/AtomicFloor.java
- src/main/java/be/uantwerpen/minelabs/block/QuantumfieldBlock.java
- src/main/java/be/uantwerpen/minelabs/block/entity/QuantumFieldBlockEntity.java
- src/main/java/be/uantwerpen/minelabs/util/MinelabsProperties.java
- src/main/java/be/uantwerpen/minelabs/util/QuantumFieldSpawner.java
Some fixes for Sub Atomic Dimension (including quantumfields, atomic floor)
> Subatom fixes

- src/main/java/be/uantwerpen/minelabs/block/entity/IonicBlockEntity.java
- src/main/java/be/uantwerpen/minelabs/block/entity/LewisBlockEntity.java
- src/main/java/be/uantwerpen/minelabs/crafting/CraftingRecipes.java
- src/main/java/be/uantwerpen/minelabs/crafting/ionic/IonicRecipe.java
- src/main/java/be/uantwerpen/minelabs/crafting/lewis/MoleculeRecipe.java
Should remove error/warn message in console. About unkown recipe type
> fixes types not properly registered

- src/main/java/be/uantwerpen/minelabs/gui/lewis_gui/LewisBlockScreenHandler.java
- src/main/java/be/uantwerpen/minelabs/gui/lewis_gui/LewisScreen.java
- src/main/java/be/uantwerpen/minelabs/util/Graph.java
- src/main/resources/assets/minelabs/lang/en_us.json
- src/main/resources/assets/minelabs/lang/nl_be.json
- src/main/resources/assets/minelabs/lang/nl_nl.json
> Lct recipe visualization

- src/main/java/be/uantwerpen/minelabs/block/AtomicFloor.java
- src/main/java/be/uantwerpen/minelabs/block/QuantumfieldBlock.java
- src/main/java/be/uantwerpen/minelabs/dimension/ModDimensions.java
- src/main/java/be/uantwerpen/minelabs/entity/EntropyCreeperEntity.java
> Entropycreeper fixes, that really are portal fixes for 50%

- src/main/java/be/uantwerpen/minelabs/gui/lewis_gui/LewisScreen.java
#502 
yes it is ugly (the code I mean) but gets the job done
> change to inputslots LCT

- .github/workflows/push.yml
> Github actions

- build.gradle
- gradle.properties
- settings.gradle
In game everything seems to work still.
> Cleanup dependencies and add DisableCustomWorldsAdvice

- src/main/java/be/uantwerpen/minelabs/item/Items.java
closes #494
Removes the description, thanks @smtdm
> removed item description for salt items

- src/main/java/be/uantwerpen/minelabs/item/ItemModels.java
> prevent creation of empty nbt tag during read only call of atom model predicate

- src/main/java/be/uantwerpen/minelabs/entity/BohrBlueprintEntity.java
Need this to get sent to the testserver, please merge :)
> compute nucleusstate in client and stability in server. closes #584

- src/main/java/be/uantwerpen/minelabs/block/BohrBlueprintBlock.java
- src/main/java/be/uantwerpen/minelabs/entity/BohrBlueprintEntity.java
> found actual reason for client/server desync in bohr entity

- src/main/java/be/uantwerpen/minelabs/item/Items.java
- src/main/resources/data/minelabs/recipes/erlenmeyer.json
- src/main/resources/data/minelabs/recipes/lasertool_diamond.json
- src/main/resources/data/minelabs/recipes/lasertool_gold.json
- src/main/resources/data/minelabs/recipes/lasertool_iron.json
> Added recipes for lasertools and erlenmeyer

- src/main/java/be/uantwerpen/minelabs/entity/BohrBlueprintEntity.java
- src/main/java/be/uantwerpen/minelabs/event/ClientModsEvents.java
- src/main/java/be/uantwerpen/minelabs/renderer/BohrBlueprintEntityRenderer.java
- src/main/java/be/uantwerpen/minelabs/renderer/BohrBlueprintHUDRenderer.java
Completely overhauled bohr rendering code.
- render electrons facing outward
- draw lines of shells
- max amount of particles rendered in nucleus, facing camera
This is the start of updating the bohr plate rendering. Still need to do instability effect and tweaking scale, speed and offsets.
> Bohr/rendering: Rework of bohr rendering code

- src/main/java/be/uantwerpen/minelabs/advancement/criterion/BohrCriterion.java
- src/main/java/be/uantwerpen/minelabs/advancement/criterion/Criteria.java
- src/main/java/be/uantwerpen/minelabs/block/BohrBlueprintBlock.java
- src/main/java/be/uantwerpen/minelabs/entity/BohrBlueprintEntity.java
- src/main/java/be/uantwerpen/minelabs/entity/SubatomicParticleEntity.java
- src/main/java/be/uantwerpen/minelabs/event/ServerModEvents.java
- src/main/resources/data/minelabs/advancements/basic/bohr_hook_item_out.json
- src/main/resources/data/minelabs/advancements/basic/make_an_atom.json
- src/main/resources/data/minelabs/advancements/basic/use_bohr_blueprint.json
Added extraction of the last inserted item from the Bohr blueprint by hooking with a fishing rod.
Added the advancement `Are you hooked yet?`, which is triggered whenever the player extracts an item by hooking.
> Added hook extraction and matching advancement

- src/main/java/be/uantwerpen/minelabs/item/ItemGroups.java
added entropy creeper to minelabs tab, closes #589
> added entropy creeper to minelabs tab 

- src/main/java/be/uantwerpen/minelabs/renderer/BohrBlueprintEntityRenderer.java
Creating a draft PR so I can leave comments
> WIP: Electron shell capacities

- src/main/java/be/uantwerpen/minelabs/item/ItemGroups.java
> Updated Itemgroups

- build.gradle
fixes #559
includes "Disable Custom Worlds Advice" in jar
> Added "Disable Custom Worlds Advice" as hard dependency

- src/main/java/be/uantwerpen/minelabs/renderer/BohrBlueprintHUDRenderer.java
> bohr HUD refactor

- src/main/java/be/uantwerpen/minelabs/renderer/BohrBlueprintEntityRenderer.java
Closes #647.
I'm not sure whether I like these yet. Might just need to get used to them but something feels off..
> orthogonalish electron shell orbits

- src/main/java/be/uantwerpen/minelabs/block/BohrBlueprintBlock.java
- src/main/java/be/uantwerpen/minelabs/entity/BohrBlueprintEntity.java
- src/main/java/be/uantwerpen/minelabs/util/MinelabsProperties.java
- src/main/resources/assets/minelabs/blockstates/bohr_block.json
Re-implemented BBP status for colored model
(Closes #607)
> Re-implemented BBP status

- .github/workflows/push.yml
SO that the correct server has the correct port for the workflow
> swapped port numbers

- src/main/java/be/minelabs/item/items/GasPotion.java
- src/main/java/be/minelabs/item/reaction/CorrosiveReaction.java
- src/main/java/be/minelabs/item/reaction/DissolveReaction.java
- src/main/java/be/minelabs/item/reaction/ExplosiveReaction.java
- src/main/java/be/minelabs/item/reaction/ExtinguishReaction.java
- src/main/java/be/minelabs/item/reaction/FlammableReaction.java
- src/main/java/be/minelabs/item/reaction/PoisonousReaction.java
- src/main/java/be/minelabs/item/reaction/Reaction.java
- src/main/java/be/minelabs/science/Molecule.java
- src/main/resources/assets/minelabs/lang/en_us.static.json
Added lore to gass erlenmeyers.
Colors are up for debate:
- RED: Explosive / Flammable
- GREEN: Poisonous
- GREY : Corrosive / Dissolve / Extinguish
Names are translatable, see static lang file. (keys can also be change if need be)
fixes #616
> Chemical Lore

- gradle.properties
- src/main/java/be/minelabs/block/Blocks.java
- src/main/java/be/minelabs/block/blocks/MologramBlock.java
- src/main/java/be/minelabs/block/entity/MologramBlockEntity.java
- src/main/java/be/minelabs/inventory/OrderedInventory.java
- src/main/java/be/minelabs/recipe/lewis/LewisCraftingGrid.java
- OrderedInventory
- Mologram no tick function
- Miscelaneous fixes
> Update OrderedInventory and fix version of structure API (main can't build now)

- src/main/resources/data/minelabs/recipes/lewis_crafting_table.json
- src/main/resources/data/minelabs/recipes/mologram.json
> Added missing recipes for LCT and Mologram

- gradle.properties
- src/client/java/be/minelabs/client/gui/screen/ChargedPointScreen.java
- src/client/java/be/minelabs/client/gui/screen/IonicScreen.java
- src/client/java/be/minelabs/client/gui/screen/LabChestScreen.java
- src/client/java/be/minelabs/client/gui/screen/LewisScreen.java
`init()` gets called evertime we the user scales the window. So we kept moving the title down on every scale "event"
> fixed title moving after "scaling" window
